### ISSUE TITLE
Update k2redirector.xml

### ISSUE THREAD

**Issue by raramuridesign** [betweenbrain/K2-Redirector#1]
Add more of a description to the XML file to understand what is going on with the selection of url's and the actual process needed to get the redirects to work.

**Comment by betweenbrain** [comment]
I've been fairly busy, and not had had a chance to get to this, but wanted to see if you had any suggestions.

**Comment by betweenbrain** [comment]
If you have a chance, please try https://github.com/betweenbrain/K2-Redirector/archive/develop.zip

**Comment by raramuridesign** [comment]
Just uploaded to a test site. do you by any chance have the links used for the 5 redirects this plugin handles, so I can test these ?

**Comment by raramuridesign** [comment]
It might also be useful to have these links mentioned on the plugin as well, then its a matter of testing from the plugin...

**Comment by betweenbrain** [comment]
The URLs have been added to the plugin README at https://github.com/betweenbrain/K2-Redirector

**Comment by raramuridesign** [comment]
Just a note on this

this link will not redirect USER View
/index.php?option=com_k2&task=user

But if you combine the following
/index.php?option=com_k2&view=itemlist&layout=category&task=user&id=8&Itemid=108

Note the task=user

It then redirect to the home page, but outputs the following
/index.php?option=com_k2&amp;view=item&amp;layout=item&amp;id=7&amp;Itemid=101

---

SEF urls on
the following works and redirects to a clean URL
/news.html?task=user

---

If Author link is activated while SEF is on, and this is shown on the front-end, behavior works as expected.

**Comment by betweenbrain** [comment]
Thanks for testing! I've updated the instructions for more real-world usage, and corrected the plugin for the user view.

**Comment by betweenbrain** [comment]
@raramuridesign not sure if you saw this, but I did update the README to clarify this.

**Comment by raramuridesign** [comment]
Yes, already tested and working, thanks.
It makes a lot of sense now.

Thank you.

**Comment by betweenbrain** [comment]
Great, thanks for testing.
